platform :ios, '7.1'
target 'iDeviant', :exclusive => true do
    pod 'MWPhotoBrowser'
    pod 'AFNetworking'
end

target 'iDeviantTests', :exclusive => true do
     pod 'MWPhotoBrowser'
     pod 'AFNetworking'
end
